// Modelo declarativo da Entrevista de Desligamento — transcrito fielmente do
// PDF "Entrevista de Desligamento - Sfera Multifranquias.pdf" (export do
// Microsoft Forms original, com "Opções de ramificação").
//
// As perguntas 1 a 17 (identificação + local de trabalho) são preenchidas
// pelo(a) analista de RH ao gerar o link (ver js/sections/entrevista-
// desligamento.js) e aparecem para o(a) ex-colaborador(a) como um resumo
// somente-leitura no topo da página pública — não são reperguntadas. O
// questionário interativo (um a um, igual ao Microsoft Forms original) vai
// da pergunta 18 ("Motivo do Desligamento") até a 83 (NPS), navegando pelo
// grafo de ramificação abaixo via o campo `next` de cada opção.
//
// "O Boticário Halfeld" aparece de propósito em duas listas (Juiz de Fora E
// Interior de MG, perguntas 6 e 9) — não é erro de digitação: o mesmo
// fenômeno já apareceu no PDF de Parecer do Gestor (O Boticário Loja),
// então foi preservado como está nos dois lugares.
(function () {
  // ---------------------------------------------------------------
  // Perguntas 5 a 17 — Unidade de trabalho + loja/ER/departamento
  // ---------------------------------------------------------------
  const UNIDADE_TRABALHO_OPCOES = [
    { label: 'Boticário - Juiz de Fora', next: 6 },
    { label: 'Boticário - Rio de Janeiro', next: 7 },
    { label: 'Boticário - Três Rios', next: 8 },
    { label: 'Boticário - Interior de MG', next: 9 },
    { label: 'Quem disse, Berenice?', next: 17 },
    { label: 'Boticário VD - Juiz de Fora', next: 10 },
    { label: 'Boticário VD - Três Rios', next: 13 },
    { label: 'Boticário VD - Rio de Janeiro', next: 11 },
    { label: 'Boticário VD - Interior de MG', next: 12 },
    { label: 'Escritório', next: 14 },
    { label: 'Levis', next: 16 },
    { label: 'Hering', next: 15 }
  ];

  // id da pergunta -> { titulo, lojas: [nomes] } — todas levam à 18.
  const LOCAIS = {
    6: { titulo: 'Selecione a loja em que trabalhou (Boticário - Juiz de Fora)', lojas: ['O Boticário Marechal', 'O Boticário Jardim Norte', 'O Boticário Independência', 'O Boticário Carrefour Rio Branco', 'O Boticário Alameda', 'O Boticário Mister', 'O Boticário Santa Cruz', 'O Boticário Halfeld'] },
    7: { titulo: 'Selecione a loja em que trabalhou (Boticário - Rio de Janeiro)', lojas: ['O Boticário Alcântara', 'O Boticário Calçadão Madu', 'O Boticário Carrefour', 'O Boticário Guanabara', 'O Boticário Madureira Shop', 'O Boticário Mercadão', 'O Boticário Norte Shop P1', 'O Boticário Norte Shop P2', 'O Boticário Partage', 'O Boticário Rodo', 'O Boticário São Gonçalo Shop', 'O Boticário Sulacap', 'O Boticário Valqueire', 'O Boticário Campinho'] },
    8: { titulo: 'Selecione a loja em que trabalhou (Boticário - Três Rios)', lojas: ['O Boticário 3R Galeria', 'O Boticário 3R Quiosque'] },
    9: { titulo: 'Selecione a loja em que trabalhou (Boticário - Interior de MG)', lojas: ['Aimorés (MG)', 'Carangola (MG)', 'Caratinga Olegário (MG)', 'Caratinga Raul (MG)', 'Espera Feliz (MG)', 'Inhapim (MG)', 'O Boticário Além Paraíba (MG)', 'O Boticário Barroso (MG)', 'O Boticário Carandaí (MG)', 'O Boticário Halfeld', 'O Boticário Ipanema (MG)', 'O Boticário Leopoldina (MG)', 'O Boticário Manhuaçu (MG)', 'O Boticário Manhumirim (MG)', 'O Boticário Raul Soares (MG)', 'O Boticário Santos Dumont (MG)'] },
    10: { titulo: 'Selecione o ER em que trabalhou (Boticário - VD Juiz de Fora)', lojas: ['O Boticário VD Sorrento Centro', 'O Boticário VD Sorrento Benfica'] },
    11: { titulo: 'Selecione o ER em que trabalhou (Boticário - VD Rio de Janeiro)', lojas: ['O Boticário VD Partage', 'O Boticário VD Madureira', 'O Boticário VD Alcântara'] },
    12: { titulo: 'Selecione o ER em que trabalhou (Boticário - VD interior de MG)', lojas: ['Aimorés VD (MG)', 'O Boticário VD Manhuaçu (MG)', 'Carangola VD (MG)', 'Caratinga VD (MG)', 'O Boticário VD Santos Dumont (MG)', 'O Boticário VD Raul Soares (MG)', 'O Boticário VD Leopoldina (MG)', 'O Boticário VD Além Paraíba (MG)'] },
    13: { titulo: 'Selecione o ER em que trabalhou (Boticário VD - Três Rios)', lojas: ['O Boticário VD Liva'] },
    15: { titulo: 'Selecione a loja em que trabalhou (Hering)', lojas: ['Hering Américas Shop', 'Hering Catete', 'Hering Copacabana', 'Hering Icaraí', 'Hering Plaza', 'Hering Rio Sul'] },
    16: { titulo: "Selecione a loja em que trabalhou (Levi's)", lojas: ['Levis Nova América', 'Levis Caxias', 'Levis Barra', 'Levis Rio Sul', 'Levis Tijuca', 'Levis Plaza', 'Levis Norte'] },
    17: { titulo: 'Selecione a loja em que trabalhou (Quem Disse, Berenice?)', lojas: ['Quem disse, Berenice? Norte'] }
  };

  const DEPARTAMENTOS = ['Administrativo', 'Auditoria', 'Comercial Hering', 'Comercial Levis', 'Comercial O Boticário MG', 'Comercial O Boticário RJ', 'Compras - Hering', 'Compras - Levis', 'Compras - O Boticário', 'Departamento Pessoal', 'Diretoria', 'Financeiro', 'Inteligência Comercial', 'Logística', 'Manutenção', 'Marketing', 'Recursos Humanos', 'Supervisão Hering', 'Supervisão Levis', 'Tecnologia da Informação'];

  // ---------------------------------------------------------------
  // Perguntas 18 a 83 — questionário interativo (grafo de ramificação)
  // ---------------------------------------------------------------
  const P = {};
  P[18] = {
    titulo: 'Motivo do Desligamento:', tipo: 'unica', opcoes: [
      { label: 'Remuneração', next: 19 }, { label: 'Benefícios', next: 20 },
      { label: 'Adaptação à Cultura Organizacional', next: 21 }, { label: 'Insatisfação com a Empresa', next: 22 },
      { label: 'Liderança', next: 23 }, { label: 'Outra Oportunidade de Trabalho', next: 24 },
      { label: 'Baixo Desempenho / Performance', next: 25 }, { label: 'Perspectiva de Crescimento', next: 26 },
      { label: 'Motivos Pessoais', next: 27 }, { label: 'Dificuldade com processo / Padrão de atendimento', next: 28 }
    ]
  };
  P[19] = { titulo: 'Remuneração', tipo: 'unica', opcoes: ['Comissionamento mais atrativo', 'Insatisfação com progressão ou política salarial', 'Outra proposta com salário mais atrativo', 'Outras remunerações variáveis'].map(label => ({ label, next: 29 })) };
  P[20] = { titulo: 'Benefícios', tipo: 'unica', opcoes: ['Plano de Saúde e Odontológico', 'Vale-Refeição/Alimentação', 'Insatisfação com acesso, qualidade ou comunicação dos benefícios', 'Outros benefícios como: Auxílio Creche, Cesta Básica, Bolsas de Estudo ou Ajuda de Custo em Cursos'].map(label => ({ label, next: 29 })) };
  P[21] = { titulo: 'Adaptação à Cultura Organizacional', tipo: 'unica', opcoes: ['Dificuldade de integração ao time', 'Estilo de liderança ou gestão', 'Conflito com valores e normas da empresa', 'Falta de clareza sobre as metas e cobranças', 'Percepção de ambiente de favoritismo ou grupo fechado'].map(label => ({ label, next: 29 })) };
  P[22] = { titulo: 'Insatisfação com a Empresa', tipo: 'unica', opcoes: ['Falta de Políticas/Critérios/Processos de reconhecimento ou valorização', 'Comunicação interna falha', 'Ambiente de trabalho desorganizado', 'Falta de processos claros e estruturados', 'Promessas não cumpridas pela empresa'].map(label => ({ label, next: 29 })) };
  P[23] = { titulo: 'Liderança', tipo: 'unica', opcoes: ['Estilo autoritário ou centralizador', 'Ausência de feedback sobre seu desempenho e desenvolvimento', 'Falta de clareza na comunicação do gestor direto', 'Falta de orientação e acompanhamento em relação às minhas atividades', 'Falta de reconhecimento pelo gestor direto', 'Comportamento inadequado / conduta imprópria do gestor', 'Percepção de favoritismo da liderança com pessoas específicas do time'].map(label => ({ label, next: 29 })) };
  P[24] = { titulo: 'Outra Oportunidade de Trabalho', tipo: 'unica', opcoes: ['Proposta de melhor cargo ou carreira', 'Modalidade de trabalho (home office, híbrido, presencial)', 'Estabilidade e projeção de crescimento na nova empresa', 'Benefícios mais vantajosos em relação aos atuais', 'Maior estabilidade ou segurança no novo emprego', 'Transição de área ou setor de atuação'].map(label => ({ label, next: 29 })) };
  P[25] = { titulo: 'Baixo Desempenho / Performance', tipo: 'unica', opcoes: ['Metas e indicadores que poderiam estar mais ajustados à realidade da operação', 'Dificuldade em compreender ou acompanhar os indicadores de desempenho', 'Não se adaptou ao estilo de atendimento ou execução das atividades', 'Desalinhamento com perfil da função', 'Dificuldade de realizar as tarefas', 'Falta de suporte em loja por parte da liderança', 'Falta de treinamento sobre indicadores de desempenho da área'].map(label => ({ label, next: 29 })) };
  P[26] = { titulo: 'Perspectiva de Crescimento', tipo: 'unica', opcoes: ['Ausência de comunicação sobre caminhos de desenvolvimento dentro da empresa', 'Sentimento de estagnação na função, sem desafios ou evolução', 'Poucas oportunidades de capacitação ou desenvolvimento profissional por parte da empresa', 'Alta demanda operacional que impedia foco em desenvolvimento', 'Mudanças constantes na estrutura ou nas diretrizes que dificultavam o crescimento', 'Falta de critérios objetivos para promoções'].map(label => ({ label, next: 29 })) };
  P[27] = { titulo: 'Motivos Pessoais', tipo: 'unica', opcoes: ['Problemas de saúde (próprios ou de familiares)', 'Dificuldade em conciliar vida pessoal e profissional', 'Distância ou dificuldade de deslocamento até o local de trabalho', 'Questões emocionais ou psicológicas que afetaram meu desempenho', 'Mudanças na rotina familiar (ex: filhos, cuidados com parentes)', 'Decisão de focar em estudos ou desenvolvimento pessoal', 'Mudança de cidade, estado ou país'].map(label => ({ label, next: 29 })) };
  P[28] = {
    titulo: 'Dificuldade com processo / Padrão de atendimento (Botileza / Pulsar / Atendimento 360 / Seams / Live in Levi\'s)', tipo: 'unica', opcoes: [
      'Falta de clareza no processo - Dificuldade de compreender totalmente o padrão exigido, mudanças frequentes sem comunicação clara, informações contraditórias entre gestores ou desalinhamento entre o que é apresentado na teoria e o que é praticado na loja.',
      'Discordância ou não identificação com o modelo - Falta de alinhamento com o formato de atendimento proposto, percepção de que o modelo não funciona na prática da unidade ou dificuldade de adaptação ao estilo da marca e ao padrão exigido.',
      'Falta de suporte da liderança para aplicar o padrão - Percepção de que o gestor não aplica o padrão como exemplo, oferece pouca orientação prática no salão, não realiza acompanhamento estruturado ou fornece feedback pouco construtivo sobre a execução.',
      'Dificuldade prática na execução - Fatores operacionais dificultam a aplicação completa do modelo, como falta de tempo devido ao fluxo da loja, equipe reduzida, acúmulo de funções ou limitações de sistema e ferramentas que impactam a execução adequada.',
      'Treinamento insuficiente - O treinamento inicial não foi suficiente para garantir segurança na execução do padrão, houve ausência de reciclagem, aprendizado majoritariamente informal com colegas ou falta de acompanhamento estruturado após o treinamento.'
    ].map(label => ({ label, next: 29 }))
  };
  P[29] = { titulo: 'Justifique sua resposta anterior', tipo: 'texto', next: 30 };
  P[30] = {
    titulo: 'Ao ingressar na Sfera Multifranquias o que mais lhe motivou a optar pela empresa foi:', tipo: 'unica', opcoes: [
      { label: 'Necessidade de trabalho', next: 32 }, { label: 'Remuneração', next: 32 }, { label: 'Possibilidade de crescimento', next: 32 },
      { label: 'Identificação com as marcas/cultura', next: 32 }, { label: 'Transição de carreira', next: 32 }, { label: 'Qualidade de vida', next: 32 },
      { label: 'Indicação', next: 32 }, { label: 'Benefícios', next: 32 }, { label: 'Outros', next: 31 }
    ]
  };
  P[31] = { titulo: 'Quais?', tipo: 'texto', next: 32 };
  P[32] = { titulo: 'As informações do PROCESSO SELETIVO, referente a remuneração, atribuições e benefícios, correspondem ao que foi aplicado?', tipo: 'unica', opcoes: [{ label: 'Sim', next: 33 }, { label: 'Não', next: 34 }, { label: 'Em parte', next: 34 }] };
  P[33] = { titulo: 'Como você avalia a clareza e a coerência das informações apresentadas durante o PROCESSO SELETIVO, especialmente em relação à remuneração, atribuições e benefícios?', tipo: 'unica', opcoes: ['As informações sobre salário, atribuições e benefícios foram apresentadas com clareza e transparência.', 'O que foi informado no processo seletivo correspondeu exatamente ao que foi aplicado.', 'A empresa demonstrou respeito ao compartilhar dados relevantes de forma objetiva e profissional.', 'As etapas e informações do processo foram conduzidas de forma justa e coerente', 'A divulgação das condições da vaga foi feita com precisão e profissionalismo.'].map(label => ({ label, next: 36 })) };
  P[34] = {
    titulo: 'Por favor, descreva abaixo o que não foi passado corretamente durante o PROCESSO SELETIVO, referente a remuneração, atribuições e benefícios.', tipo: 'unica', opcoes: [
      { label: 'Valor da remuneração ou composição salarial (fixo, variável, comissões) - Entrevista com a Gestão', next: 36 },
      { label: 'Apresentação da Composição Salarial - Entrevista com o RH', next: 36 },
      { label: 'Descrição clara das atribuições e responsabilidades do cargo - Entrevista com o RH', next: 36 },
      { label: 'Detalhamento dos benefícios oferecidos (vale-transporte, alimentação, plano de saúde, etc.) - Entrevista com o RH', next: 36 },
      { label: 'Diferenças entre o que foi dito pelo RH e o que foi dito pela liderança', next: 35 }
    ]
  };
  P[35] = { titulo: 'Esclareça em detalhes, quais as diferenças você percebeu entre as informações compartilhadas pelo RH e aquelas transmitidas pela liderança?', tipo: 'texto', next: 36 };
  P[36] = { titulo: 'As informações do PROCESSO DE CONTRATAÇÃO, referente a remuneração, benefícios, jornada de trabalho, correspondem ao que foi aplicado?', tipo: 'unica', opcoes: [{ label: 'Sim', next: 37 }, { label: 'Não', next: 38 }, { label: 'Em parte', next: 38 }] };
  P[37] = { titulo: 'Se sim, como você avalia essa experiência no PROCESSO DE CONTRATAÇÃO?', tipo: 'unica', opcoes: ['Muito satisfeito – As informações foram claras, completas e totalmente condizentes com a realidade', 'Satisfeito – Houve alinhamento entre o que foi informado e o que foi vivenciado.', 'Parcialmente satisfeito – As informações foram corretas, mas poderiam ter sido mais detalhadas.', 'Surpreendido positivamente – A prática superou as expectativas criadas durante o processo.', 'Confiante na empresa – A transparência nas informações reforçou minha confiança na organização.'].map(label => ({ label, next: 39 })) };
  P[38] = { titulo: 'Por favor, descreva abaixo o que não foi passado corretamente durante o PROCESSO DE CONTRATAÇÃO, referente a remuneração, benefícios, jornada de trabalho, correspondem ao que foi aplicado?', tipo: 'unica', opcoes: ['Não houve espaço para tirar dúvidas antes ou logo após a contratação', 'Expectativas de desempenho e metas não foram bem explicadas', 'Política de pagamento (datas, descontos, adicionais, etc.)', 'Horários de trabalho, escalas e pausas não foram explicados adequadamente', 'Não houve informações sobre a Política de Vale-Transporte'].map(label => ({ label, next: 39 })) };
  P[39] = { titulo: 'Você considera o ONBOARDING e os treinamentos iniciais aderentes às tarefas desempenhadas?', tipo: 'unica', opcoes: [{ label: 'Sim', next: 40 }, { label: 'Não', next: 41 }, { label: 'Em parte', next: 41 }, { label: 'Não tive treinamento', next: 41 }] };
  P[40] = { titulo: 'Se sim, como você avalia essa experiência no nosso ONBOARDING?', tipo: 'unica', opcoes: ['Muito satisfatório – O conteúdo foi completo, bem estruturado e diretamente aplicável às atividades do dia a dia.', 'Satisfatório – Os treinamentos e o onboarding foram úteis e ajudaram na adaptação às tarefas.', 'Prático e objetivo – As informações foram claras e focadas nas demandas reais do cargo.', 'Facilitou a integração – O processo inicial contribuiu para uma ambientação rápida e eficiente.', 'Preparação adequada – Me senti preparado para iniciar as atividades com segurança e autonomia.'].map(label => ({ label, next: 42 })) };
  P[41] = { titulo: 'Você poderia compartilhar quais aspectos do ONBOARDING ou dos treinamentos iniciais não atenderam às demandas do seu dia a dia? Há algo específico que você acredita que deveria ter sido abordado?', tipo: 'multipla', maxSelecionar: 2, next: 42, opcoes: ['As atividades abordadas nos treinamentos iniciais não corresponderam às tarefas realizadas no dia a dia', 'A didática utilizada nos treinamentos iniciais não facilitou a compreensão das tarefas práticas do dia a dia', 'Faltou orientação sobre ferramentas, sistemas ou processos utilizados na rotina', 'Não houve explicação suficiente sobre a cultura da empresa e seus valores', 'Não houve espaço para tirar dúvidas ou receber acompanhamento nos primeiros dias', 'Faltou orientação sobre treinamentos obrigatórios ou iniciais', 'Não tive acompanhamento ou a pessoa que me acompanhou não dedicou tempo de qualidade'].map(label => ({ label })) };
  P[42] = { titulo: 'Como você avalia a quantidade de TREINAMENTOS OBRIGATÓRIOS durante sua permanência na empresa?', tipo: 'unica', opcoes: [{ label: 'Satisfatório', next: 43 }, { label: 'Adequada à função e rotina', next: 43 }, { label: 'Excessiva, atrapalhou a rotina de trabalho', next: 44 }, { label: 'Um pouco acima do necessário', next: 44 }, { label: 'Insuficiente, senti falta de mais capacitações', next: 44 }] };
  P[43] = { titulo: 'Qual a opção que melhor representa sua experiência em relação aos TREINAMENTOS OBRIGATÓRIOS?', tipo: 'unica', opcoes: ['Muito adequada – A quantidade de treinamentos foi equilibrada e contribuiu significativamente para meu desenvolvimento.', 'Suficiente – Os treinamentos obrigatórios atenderam bem às necessidades do cargo.', 'Bem distribuída – Os treinamentos foram aplicados em momentos oportunos, sem sobrecarga.', 'Enriquecedora – A frequência dos treinamentos ajudou a manter o aprendizado contínuo.', 'Organizada e coerente – A quantidade foi bem planejada e alinhada com as exigências da função.'].map(label => ({ label, next: 45 })) };
  P[44] = { titulo: 'O que poderia ser melhor em relação aos TREINAMENTOS OBRIGATÓRIOS?', tipo: 'multipla', maxSelecionar: 2, next: 45, opcoes: ['Melhor alinhamento entre conteúdo e rotina prática da função', 'Redução da carga horária dos treinamentos', 'Maior objetividade e clareza nos temas abordados', 'Mais flexibilidade de horários para realização dos treinamentos', 'Treinamentos mais interativos e dinâmicos', 'Menor repetição de conteúdos já conhecidos', 'Inclusão de temas mais relevantes para o cargo', 'Melhor planejamento e distribuição ao longo do tempo', 'Treinamentos com foco em desenvolvimento técnico e comportamental', 'Maior integração entre áreas durante os treinamentos', 'Maior equilíbrio entre os treinamentos e a rotina de trabalho, respeitando os fluxos do dia a dia.'].map(label => ({ label })) };
  P[45] = { titulo: 'Como você considera a COMUNICAÇÃO DA EMPRESA, em relação às políticas, diretrizes e normas?', tipo: 'unica', opcoes: [{ label: 'Muito clara', next: 46 }, { label: 'Clara', next: 46 }, { label: 'Razoável', next: 47 }, { label: 'Pouco clara', next: 47 }, { label: 'Inexistente ou desconhecida', next: 47 }] };
  P[46] = { titulo: 'Qual a opção que melhor representa sua experiência com a COMUNICAÇÃO DA EMPRESA?', tipo: 'unica', opcoes: ['Muito clara e acessível – As informações foram sempre bem comunicadas e de fácil entendimento.', 'Bem estruturada – As políticas e normas foram apresentadas de forma organizada e consistente.', 'Transparente – A empresa manteve uma comunicação aberta e honesta sobre suas diretrizes.', 'Regular e atualizada – As informações foram transmitidas com frequência e atualizadas quando necessário.', 'Facilitadora da rotina – A comunicação ajudou a aplicar corretamente as normas no dia a dia de trabalho.'].map(label => ({ label, next: 48 })) };
  P[47] = { titulo: 'Compartilhe situações em que a COMUNICAÇÃO DA EMPRESA não foi clara, ou em que informações importantes não foram transmitidas de maneira adequada ou com a antecedência necessária.', tipo: 'multipla', maxSelecionar: 2, next: 48, opcoes: ['Mudanças em políticas internas comunicadas sem antecedência ou explicação', 'Alterações de horário ou escala informadas em cima da hora', 'Normas de conduta ou procedimentos operacionais pouco divulgados ou mal explicados', 'Falta de canais claros para tirar dúvidas sobre regras e diretrizes', 'Diretrizes da liderança mudavam com frequência e sem comunicação formal', 'Informações diferentes vindas de líderes distintos, gerando confusão', 'Comunicados importantes enviados por canais pouco acessíveis ou não utilizados pela equipe', 'Atualizações sobre benefícios, folha de pagamento ou normas internas não foram bem explicadas', 'Campanhas comerciais ou ações de loja comunicadas com pouco tempo para execução', 'Falta de alinhamento entre áreas (ex: loja e escritório) sobre processos e decisões'].map(label => ({ label })) };
  P[48] = { titulo: 'Como avalia o relacionamento com seu GESTOR DIRETO?', tipo: 'unica', opcoes: [{ label: 'Excelente, havia abertura, apoio e boa comunicação', next: 49 }, { label: 'Bom, com interações produtivas e respeitosas', next: 49 }, { label: 'Regular, com pontos que poderiam ser melhorados', next: 50 }, { label: 'Difícil, com falhas na comunicação ou falta de apoio', next: 50 }] };
  P[49] = { titulo: 'Qual a opção que melhor representa seu relacionamento com seu GESTOR DIRETO?', tipo: 'unica', opcoes: ['Muito positivo – Havia abertura, respeito e apoio constante na rotina de trabalho.', 'Colaborativo – O gestor estava sempre disponível para orientar e contribuir com o desenvolvimento.', 'Respeitoso e profissional – O relacionamento foi baseado em ética, confiança e boa comunicação.', 'Inspirador – O gestor atuou como exemplo e incentivou o crescimento profissional.', 'Construtivo – As trocas foram produtivas e contribuíram para meu desempenho e aprendizado.'].map(label => ({ label, next: 51 })) };
  P[50] = { titulo: 'Sinalize o que poderia ser melhor ou o que não era bom no relacionamento com seu GESTOR DIRETO.', tipo: 'multipla', maxSelecionar: 2, next: 51, opcoes: ['Falta de comunicação clara e frequente sobre expectativas de carreira', 'Pouco apoio ou disponibilidade para tirar dúvidas e orientar', 'Feedbacks escassos ou pouco construtivos sobre o desempenho', 'Falta de direcionamento sobre prioridades e organização das tarefas', 'Relacionamento distante ou pouco empático', 'Dificuldade em lidar com conflitos ou situações delicadas', 'Falta de compreensão em relação a demandas pessoais', 'Pouco incentivo ao desenvolvimento profissional ou treinamentos', 'Decisões tomadas sem envolver ou considerar a equipe', 'Falta de reconhecimento pelos resultados e esforços individuais', 'Falta de comunicação clara e frequente sobre metas e resultados'].map(label => ({ label })) };
  P[51] = { titulo: 'Como você considera a gestão do seu SUPERIOR IMEDIATO?', tipo: 'unica', opcoes: [{ label: 'Excelente, com liderança inspiradora e bem estruturada', next: 52 }, { label: 'Boa, com direcionamentos claros e apoio adequado', next: 52 }, { label: 'Regular, com pontos que poderiam ser melhorados', next: 53 }, { label: 'Fraca, com falhas na condução e falta de alinhamento', next: 53 }, { label: 'Não tive contato suficiente para avaliar', next: 53 }] };
  P[52] = { titulo: 'Qual a opção que melhor representa a gestão do seu SUPERIOR IMEDIATO?', tipo: 'unica', opcoes: ['Muito eficiente – A liderança foi clara, organizada e alinhada com os objetivos da equipe.', 'Inspiradora – O gestor demonstrou visão estratégica e motivou o time com atitudes positivas.', 'Apoiada em diálogo – Havia abertura para conversas, escuta ativa e resolução de conflitos.', 'Focada em desenvolvimento – O gestor incentivou o crescimento profissional e ofereceu feedbacks construtivos.', 'Presente e acessível – A gestão foi próxima, disponível e comprometida com o bem-estar da equipe.'].map(label => ({ label, next: 55 })) };
  P[53] = { titulo: 'Você poderia detalhar por que considera a gestão do seu SUPERIOR IMEDIATO insatisfatória?', tipo: 'unica', opcoes: [{ label: 'Falta de apoio ou acompanhamento – O gestor não acompanhava meu trabalho ou não oferecia suporte.', next: 55 }, { label: 'Falta de clareza na comunicação – As orientações eram confusas ou inexistentes.', next: 55 }, { label: 'Falta de reconhecimento ou valorização – Meu esforço e desempenho não eram reconhecidos.', next: 55 }, { label: 'Postura autoritária ou pouco acessível – Havia dificuldade de diálogo ou abertura para sugestões.', next: 55 }, { label: 'Outros (especifique)', next: 54 }] };
  P[54] = { titulo: 'Você poderia descrever com mais detalhes o motivo pelo qual considera a gestão do seu SUPERIOR IMEDIATO insatisfatória?', tipo: 'texto', next: 55 };
  P[55] = { titulo: 'Como avalia o relacionamento com SUA EQUIPE?', tipo: 'unica', opcoes: [{ label: 'Excelente, havia colaboração, respeito e bom clima', next: 56 }, { label: 'Bom, com interações positivas e produtivas', next: 56 }, { label: 'Regular, com alguns desafios de convivência', next: 57 }, { label: 'Difícil, com conflitos ou falta de integração', next: 57 }] };
  P[56] = { titulo: 'Selecione a opção que melhor representa sua experiência com o relacionamento com SUA EQUIPE?', tipo: 'unica', opcoes: ['Muito positivo – Havia colaboração, respeito e bom clima entre os membros da equipe.', 'Integrado – A equipe trabalhava de forma unida e alinhada com os objetivos comuns.', 'Apoiado pela comunicação – A troca de informações era clara e facilitava o trabalho em grupo.', 'Ambiente acolhedor – Fui bem recebido e me senti parte do time desde o início.', 'Estimulante – O relacionamento com a equipe contribuiu para meu crescimento e motivação.'].map(label => ({ label, next: 58 })) };
  P[57] = { titulo: 'Sinalize quais aspectos do relacionamento com SUA EQUIPE você considera que poderiam ter sido melhores?', tipo: 'multipla', maxSelecionar: 2, next: 58, opcoes: ['Falta de colaboração e apoio entre os membros da equipe', 'A comunicação entre a equipe era falha ou pouco transparente', 'Ambiente de trabalho com pouca empatia ou respeito mútuo', 'Falta de alinhamento sobre objetivos e responsabilidades', 'Conflitos não resolvidos ou mal gerenciados', 'Pouca abertura para sugestões, ideias ou participação', 'Desigualdade na divisão de tarefas ou sobrecarga de alguns membros', 'Falta de comprometimento ou engajamento de parte da equipe', 'Pouca troca de conhecimento ou apoio no desenvolvimento profissional', 'Ausência de espírito de equipe ou senso de pertencimento'].map(label => ({ label })) };
  P[58] = { titulo: 'O que você acha que poderia ser feito para melhorar a sua EXPERIÊNCIA DE TRABALHO na empresa?', tipo: 'multipla', maxSelecionar: 2, next: 59, opcoes: ['Melhorar a comunicação interna entre áreas e níveis hierárquicos', 'Oferecer mais treinamentos práticos e contínuos para desenvolvimento profissional', 'Fortalecer o acolhimento e integração de novos colaboradores', 'Definir com mais clareza as funções, metas e expectativas de cada cargo', 'Promover uma cultura de feedback mais frequente e construtiva', 'Fomentar um ambiente mais colaborativo, respeitoso e empático', 'Revisar políticas de jornada, escalas e pausas para maior equilíbrio', 'Aumentar a transparência sobre salários, benefícios', 'Reconhecer mais os esforços e resultados individuais e coletivos', 'Investir em infraestrutura, ferramentas e sistemas que facilitem o trabalho', 'Aumentar a transparência sobre oportunidades de crescimento'].map(label => ({ label })) };
  P[59] = { titulo: 'Quantos FEEDBACKS você recebeu sobre o seu desempenho durante sua permanência na empresa?', tipo: 'unica', opcoes: [{ label: 'Nenhum', next: 61 }, { label: '1 a 3', next: 60 }, { label: '4 a 6', next: 60 }, { label: '7 a 9', next: 60 }, { label: 'Mais de 10', next: 60 }] };
  P[60] = { titulo: 'Como você avalia essa prática de FEEDBACKS recebidos?', tipo: 'unica', opcoes: ['Recebi feedbacks frequentes e construtivos – Foram úteis para meu desenvolvimento e alinhamento com as expectativas.', 'Recebi feedbacks em momentos estratégicos – Vieram em períodos importantes e pontuais que ajudaram a ajustar minha atuação.', 'Recebi feedbacks formais e bem estruturados – A empresa manteve uma rotina clara de avaliação e retorno.', 'Recebi feedbacks informais, mas eficazes – Mesmo sem formalidade, contribuíram para meu crescimento.', 'Recebi feedbacks que reforçaram meu desempenho – Foram positivos e motivadores, reconhecendo minhas entregas.', 'Recebi poucos Feedbacks – Poderiam ter acontecido com maior frequência.'].map(label => ({ label, next: 63 })) };
  P[61] = { titulo: 'Você poderia detalhar por que considera insatisfatória a quantidade de FEEDBACKS recebidos?', tipo: 'unica', opcoes: [{ label: 'Nunca recebi feedback espontâneo da liderança – Só tive retorno quando eu mesmo solicitei.', next: 63 }, { label: 'Faltou uma cultura de feedback contínuo – A empresa não incentivava esse tipo de prática.', next: 63 }, { label: 'Falta de tempo ou prioridade da liderança – Os líderes não priorizavam momentos de devolutiva.', next: 63 }, { label: 'Feedbacks superficiais ou genéricos – Quando aconteciam, não traziam contribuições reais.', next: 63 }, { label: 'Outros (especifique)', next: 62 }] };
  P[62] = { titulo: 'Você poderia descrever com mais detalhes por que considera insatisfatória a quantidade de FEEDBACKS recebidos?', tipo: 'texto', next: 63 };
  P[63] = { titulo: 'Em relação as outras áreas da empresa, quando houve necessidade de obter informações para auxiliar seu trabalho, você foi prontamente atendido?', tipo: 'unica', opcoes: [{ label: 'Sempre fui bem atendido (a)', next: 64 }, { label: 'Quase sempre fui bem atendido (a)', next: 64 }, { label: 'Quase nunca fui bem atendido (a)', next: 65 }, { label: 'Nunca fui bem atendido (a)', next: 65 }, { label: 'Não sabia onde procurar ajuda', next: 66 }, { label: 'Meu gestor imediato não permitia que eu buscasse apoio externo, mesmo quando ele próprio não tinha a informação necessária para me orientar.', next: 66 }] };
  P[64] = { titulo: 'Como você avalia essa experiência?', tipo: 'unica', opcoes: ['Muito colaborativo – As áreas foram ágeis, disponíveis e prestativas sempre que precisei.', 'Atendimento eficiente – Recebi as informações com rapidez e clareza, facilitando meu trabalho.', 'Boa comunicação entre áreas – Havia integração e alinhamento entre os setores.', 'Facilidade de acesso – Foi fácil identificar e contatar as pessoas certas para obter apoio.', 'Ambiente cooperativo – As áreas demonstraram espírito de equipe e disposição para ajudar.'].map(label => ({ label, next: 66 })) };
  P[65] = { titulo: 'Você poderia detalhar por que considera que o atendimento das outras áreas não foi satisfatório?', tipo: 'unica', opcoes: ['Não, nunca fui atendido – As áreas não colaboravam ou ignoravam minhas solicitações.', 'Raramente fui atendido – Tive muita dificuldade em obter informações quando precisei.', 'Fui atendido com demora ou resistência – As respostas vinham, mas com atraso ou falta de disposição.', 'Fui atendido apenas após insistência – Precisei reforçar o pedido várias vezes para conseguir retorno.', 'Fui atendido, mas com informações incompletas – As respostas não eram suficientes para resolver a demanda.'].map(label => ({ label, next: 66 })) };
  P[66] = { titulo: 'Como você classificaria os seguintes aspectos de nossa empresa em relação a REMUNERAÇÃO:', tipo: 'unica', opcoes: [{ label: 'Excelente', next: 67 }, { label: 'Bom', next: 67 }, { label: 'Regular', next: 68 }, { label: 'Ruim', next: 68 }] };
  P[67] = { titulo: 'Se considera positiva, selecione a opção que melhor representa sua experiência:', tipo: 'unica', opcoes: ['Justa e compatível com o mercado – A remuneração está alinhada com as práticas do setor e com as responsabilidades do cargo.', 'Reconhece o desempenho – Há valorização do esforço e entrega dos colaboradores.', 'Clara e bem comunicada – As regras e critérios de remuneração foram sempre bem explicados.', 'Motivadora – A remuneração contribuiu para meu engajamento e satisfação profissional.', 'Complementada por benefícios atrativos – O pacote total (salário + benefícios) foi equilibrado e satisfatório.'].map(label => ({ label, next: 70 })) };
  P[68] = { titulo: 'Você poderia detalhar por que considera a REMUNERAÇÃO da empresa insatisfatória?', tipo: 'multipla', maxSelecionar: 2, next: 69, opcoes: ['Salário abaixo do praticado no mercado', 'Falta de reconhecimento financeiro pelo desempenho', 'Pouca transparência nos critérios de remuneração', 'Benefícios pouco atrativos ou mal comunicados', 'Desigualdade salarial entre cargos ou áreas', 'Outros (especifique)'].map(label => ({ label })) };
  P[69] = { titulo: 'Você poderia descrever com mais detalhes o motivo pelo qual considera a REMUNERAÇÃO insatisfatória?', tipo: 'texto', next: 70 };
  P[70] = { titulo: 'Como você classificaria os seguintes aspectos de nossa empresa em relação a BENEFÍCIOS onde:', tipo: 'unica', opcoes: [{ label: 'Excelente', next: 71 }, { label: 'Bom', next: 71 }, { label: 'Regular', next: 72 }, { label: 'Ruim', next: 72 }] };
  P[71] = { titulo: 'Se considera positiva, selecione a opção que melhor representa sua experiência.', tipo: 'unica', opcoes: ['Muito satisfatórios – Os benefícios atendem bem às necessidades dos colaboradores e agregam valor à remuneração.', 'Competitivos – Estão alinhados com o mercado e contribuem para a retenção de talentos.', 'Bem comunicados – As informações sobre os benefícios foram claras e acessíveis desde o início.', 'Diversificados – A empresa oferece opções que contemplam diferentes perfis e necessidades.', 'Complementares ao bem-estar – Os benefícios contribuíram para minha qualidade de vida e equilíbrio profissional.'].map(label => ({ label, next: 74 })) };
  P[72] = { titulo: 'Você poderia detalhar por que considera os BENEFÍCIOS da empresa insatisfatórios?', tipo: 'unica', opcoes: [{ label: 'Poucos benefícios oferecidos – A empresa oferecia um pacote muito limitado.', next: 74 }, { label: 'Benefícios com pouca utilidade prática – Os benefícios não atendiam às minhas necessidades reais.', next: 74 }, { label: 'Falta de transparência sobre os benefícios disponíveis – Não havia comunicação clara sobre o que era oferecido.', next: 74 }, { label: 'Diferença de benefícios entre áreas ou cargos – Percebi desigualdade no acesso aos benefícios.', next: 74 }, { label: 'Outros (especifique)', next: 73 }] };
  P[73] = { titulo: 'Você poderia descrever com mais detalhes o motivo pelo qual considera os BENEFÍCIOS insatisfatórios?', tipo: 'texto', next: 74 };
  P[74] = { titulo: 'Como você classificaria os seguintes aspectos de nossa empresa em relação a POSSIBILIDADE DE CRESCIMENTO onde:', tipo: 'unica', opcoes: [{ label: 'Excelente', next: 75 }, { label: 'Bom', next: 75 }, { label: 'Regular', next: 76 }, { label: 'Ruim', next: 76 }] };
  P[75] = { titulo: 'Se considera positiva, selecione a opção que melhor representa sua experiência', tipo: 'unica', opcoes: ['Muito promissora – A empresa oferece caminhos claros e reais para evolução na carreira.', 'Bem estruturada – Existem planos e critérios definidos para promoção e desenvolvimento.', 'Estimulante – O ambiente incentiva o crescimento por meio de desafios e oportunidades.', 'Apoiada pela liderança – Os gestores incentivam e apoiam o desenvolvimento dos colaboradores.', 'Acompanhada por treinamentos – O crescimento é viabilizado por capacitações e formações internas.'].map(label => ({ label, next: 78 })) };
  P[76] = { titulo: 'Você poderia detalhar por que considera a POSSIBILIDADE DE CRESCIMENTO na empresa insatisfatória?', tipo: 'unica', opcoes: [{ label: 'Falta de plano de carreira estruturado – Não havia caminhos claros para evolução profissional.', next: 78 }, { label: 'Ausência de oportunidades internas – As promoções ou movimentações eram raras ou inexistentes.', next: 78 }, { label: 'Critérios de crescimento pouco transparentes – Não era claro o que era necessário para crescer.', next: 78 }, { label: 'Falta de reconhecimento de desempenho – Mesmo com bons resultados, não havia valorização.', next: 78 }, { label: 'Outros (especifique)', next: 77 }] };
  P[77] = { titulo: 'Você poderia descrever com mais detalhes o motivo pelo qual considera a POSSIBILIDADE DE CRESCIMENTO insatisfatória?', tipo: 'texto', next: 78 };
  P[78] = { titulo: 'Em casos de pedido de demissão, você recebeu uma nova proposta de emprego? Caso positivo, poderia mencionar: empresa, cargo e jornada de trabalho?', tipo: 'texto', next: 79 };
  P[79] = { titulo: 'Gostaria de acrescentar algum comentário ou sugestão para melhoria?', tipo: 'texto', next: 80 };
  P[80] = { titulo: 'Você trabalharia novamente na Sfera Multifranquias?', tipo: 'unica', opcoes: ['Sim, com certeza', 'Provavelmente sim', 'Talvez, dependendo das condições', 'Provavelmente não', 'Não trabalharia novamente'].map(label => ({ label, next: 81 })) };
  P[81] = { titulo: 'Por qual motivo?', tipo: 'texto', next: 82 };
  P[82] = { titulo: 'Durante sua trajetória na empresa, houve colaboradores que você considera como referências positivas, mesmo não ocupando cargos de liderança? Se sim, quem são e por que você os considera dessa forma?', tipo: 'texto', next: 83 };
  P[83] = { titulo: 'Qual é a probabilidade de você nos recomendar a um amigo ou a um colega?', tipo: 'nps', next: null };

  window.HUB_ED_MODELO = {
    PRIMEIRA_PERGUNTA: 18,
    UNIDADE_TRABALHO_OPCOES, LOCAIS, DEPARTAMENTOS, PERGUNTAS: P
  };
})();
